In [2]:
import pandas as pd
import re

In [64]:
#df=pd.read_csv('KechTweets2.csv',sep=';',encoding='utf-8',error_bad_lines=False)

In [67]:
#df.to_csv('tweet_kechCleaned.csv',sep=';',encoding='utf-8',index=False)

In [61]:
#df.drop_duplicates(inplace = True)

In [88]:
from datetime import date
for i,d in enumerate(df['date_of_review']):
    try:
        date=datetime.datetime.strptime(d, '%B %Y')
        date=date.strftime('%B %Y')
        df['date_of_review'][i]=date
    except:
        df.drop(i)

In [45]:
for i,d in enumerate(df['date_of_review']):
    if(d==''):
        df.drop(i)

# merge tweets after cleaning dates on one format

In [76]:
kech=pd.read_excel('kechcleanedwithexcel.xlsx')
kech

,hotel_name,ville,review,date_of_review,reviewer_username,reviewer_location,likes
0,Ryad Marrakech,Marrakech,REAL ESTATE IDF Marrakech RYAD in the heart of...,April 2010,trefleannonces,France,0.0
1,Ryad Marrakech,Marrakech,What envy Technical stop to refresh and contin...,April 2010,guscall,"París, Francia",NaN
2,Ryad Marrakech,Marrakech,Technical stop to refresh and continue walking...,April 2010,Fotomaf,"Madrid, España",NaN
3,Ryad Marrakech,Marrakech,Vds flight Marrakech - Girona Saturday April R...,April 2010,lavoc,france,NaN
4,Ryad Marrakech,Marrakech,Vds place Marrakech - Girona Saturday April Ry...,April 2010,lavoc,france,NaN
...,...,...,...,...,...,...,...
16703,Marrakech House,Marrakech,Good afternoon Marrakech ## coucherdesoleil @ ...,September 2020,CamelSafaries,Morocco,0.0
16704,Marrakech House,Marrakech,"📷 raoul-dufy: The house in Marrakech, Raoul Du...",September 2020,NaN,NaN,NaN
16705,Marrakech House,Marrakech,House Decorating Spectacular Outdoor! Le Riad ...,September 2020,ahomeideas,NaN,0.0
16706,Marrakech House,Marrakech,Architectural Meccas of the World: Marrakech,September 2020,bromandrealty,Waterloo,1.0
16707,Marrakech House,Marrakech,Architectural Meccas of the World: Marrakech,September 2020,bromandrealty,Waterloo,0.0

In [72]:
agadir=pd.read_csv('tweet_agadirCleaned.csv',sep=';',encoding='utf-8')
agadir

,hotel_name,ville,review,date_of_review,reviewer_username,reviewer_location,likes
0,Caribbean Village Agador,agadir,You can now book this #trip to Caribbean Villa...,March 2020,ticketstunter,Nederland,0
1,Caribbean Village Agador,agadir,#ATOLTheWayToAgadir is in full swing now 😎 (@ ...,February 2020,TVPaulD,London,2
2,Caribbean Village Agador,agadir,à The Caribbean Village Agador,October 2019,FRMHB2,NaN,0
3,Caribbean Village Agador,agadir,El Pueblo Tamlelt (Caribbean Village Agador) H...,April 2019,gouldie7,"South Yorkshire, UK",0
4,Caribbean Village Agador,agadir,El Pueblo Tamlelt (Caribbean Village Agador) H...,April 2019,jprendyuk,"Liverpool, England",0
...,...,...,...,...,...,...,...
670,HAMILTON Agadir,agadir,"David Hamilton, Two sisters, Agadir, 1970",October 2016,bleu63,FRANCE,3
671,HAMILTON Agadir,agadir,Not a cloud in the sky but our guests are be...,June 2016,CapeEnrage,"Waterside NB, Canada",0
672,HAMILTON Agadir,agadir,High heavy metal contamination found in whales...,June 2010,1darts,Salt Lake City,0
673,Agyad Maroc Hotel,agadir,hilal has added Brain Maroc to,October 2017,1Morocco_dotcom,NaN,0
674,Agyad Maroc Hotel,agadir,travel,March 2013,TravelCheaply1,UK,0

In [73]:
north=pd.read_csv('tweet_northCleaned.csv',sep=';',encoding='utf-8')
north

,hotel_name,ville,review,date_of_review,reviewer_username,reviewer_location,likes
0,Casa Perleta,Chefchaouene,I love our patio oasis here (and reprieve from...,September 2018,AndyMetzMusic,"Oakland, CA",0
1,Casa Perleta,Chefchaouene,RT : Blue has been taken seriously in Chefchao...,June 2017,YElabiad,Morocco,0
2,Casa Perleta,Chefchaouene,RT : Blue has been taken seriously in Chefchao...,June 2017,SaveMyHorses,NaN,0
3,Casa Perleta,Chefchaouene,Blue has been taken seriously in Chefchaouene ...,June 2017,penandpalate,"Puerto Vallarta, Jalisco, Mexico",5
4,Marina Bay,Tangier,"A year ago, Singapore, Marina Bay Gardens It's...",January 2021,e_andreeva,"Saint-Petersburg, Russia",0
...,...,...,...,...,...,...,...
1474,Mirador Golf Appart-hotel,Cabo Negro,"traveling to Tetouan, Cabo Negro, Mirador Golf...",August 2019,Mehdimouchtar,NaN,0
1475,Mirador Golf Appart-hotel,Cabo Negro,Cabo Negro: One night for in a Studio at the M...,June 2013,Okeydeal,NaN,0
1476,Hotel Mauritania,Tangier,"Nice view: Hotel Mauritania Centre Tanger, Tan...",January 2016,vofnmaurita,Mauritania,0
1477,Hotel Mauritania,Tangier,📷 Biggest boat in tangier (en Hotel Mauritania...,December 2015,Koukouhmohamed,"Tangier Medina, Morocco",0
1478,Hotel Mauritania,Tangier,Biggest boat in tangier @ Hotel Mauritania Tan...,December 2015,Koukouhmohamed,"Tangier Medina, Morocco",0

In [82]:
data = kech.append(agadir).append(north)
data.reset_index(drop=True, inplace=True)
data.to_csv('tweets_Cleaned.csv',sep=';',encoding='utf-8',index=False)

# Merging the booking files

In [89]:
kech=pd.read_csv('KECHBOOKINGREV.csv',encoding='utf-8',error_bad_lines=False)
kech

C:\Users\ATLAS PRO ELECTRO\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
b'Skipping line 1690: expected 8 fields, saw 13\nSkipping line 2081: expected 8 fields, saw 11\nSkipping line 10576: expected 8 fields, saw 10\nSkipping line 10580: expected 8 fields, saw 9\nSkipping line 11634: expected 8 fields, saw 10\nSkipping line 14565: expected 8 fields, saw 11\nSkipping line 18808: expected 8 fields, saw 11\nSkipping line 20627: expected 8 fields, saw 13\n'

,hotel_name,ville,review,type_rev,stay_date,reviewer_rate,reviewer_name,reviewer_country
0,Riad 7 Saints,Marrakech,Very friendly stuff! It was awesome to got so ...,pos,March 2020,10,Jan,Germany
1,Riad 7 Saints,Marrakech,This Riad surprised me in every way The facil...,pos,February 2020,NaN,NaN,NaN
2,Riad 7 Saints,Marrakech,You can hear almost everything that happens ou...,neg,February 2020,8.3,Elisa,NaN
3,Riad 7 Saints,Marrakech,The host was very friendly and accommodating ...,pos,January 2020,10,Andrean,Estonia
4,Riad 7 Saints,Marrakech,- Ridal was really a help for us! He was total...,pos,January 2020,9.0,Axel,Belgium
...,...,...,...,...,...,...,...,...
20998,Hotel Marrakech le Tichka,Marrakech,Bedrooms not 4 star in desperate need of paint...,neg,September 2019,6.7,Joanne,NaN
20999,Hotel Marrakech le Tichka,Marrakech,Rooms were dirty - toilets and bed sheets Ther...,neg,August 2019,2.9,Ahmed,Egypt
21000,Hotel Marrakech le Tichka,Marrakech,This hotel appears to be completely dysfunctio...,floors so filthy,made to wait hour on arriving and disinterest...,also pool side had dirty nappies in the garde...,neg,August 2019
21001,Hotel Marrakech le Tichka,Marrakech,Architecture,pos,July 2019,7.5,Aimar,Estonia
21002,Hotel Marrakech le Tichka,Marrakech,service,neg,July 2019,7.5,Aimar,Estonia

# #reforming dates

In [90]:
from datetime import date
for i,d in enumerate(kech['stay_date']):
    try:
        date=datetime.datetime.strptime(d, '%B %Y')
    except:
        kech.drop(i)
kech

,hotel_name,ville,review,type_rev,stay_date,reviewer_rate,reviewer_name,reviewer_country
0,Riad 7 Saints,Marrakech,Very friendly stuff! It was awesome to got so ...,pos,March 2020,10,Jan,Germany
1,Riad 7 Saints,Marrakech,This Riad surprised me in every way The facil...,pos,February 2020,NaN,NaN,NaN
2,Riad 7 Saints,Marrakech,You can hear almost everything that happens ou...,neg,February 2020,8.3,Elisa,NaN
3,Riad 7 Saints,Marrakech,The host was very friendly and accommodating ...,pos,January 2020,10,Andrean,Estonia
4,Riad 7 Saints,Marrakech,- Ridal was really a help for us! He was total...,pos,January 2020,9.0,Axel,Belgium
...,...,...,...,...,...,...,...,...
20998,Hotel Marrakech le Tichka,Marrakech,Bedrooms not 4 star in desperate need of paint...,neg,September 2019,6.7,Joanne,NaN
20999,Hotel Marrakech le Tichka,Marrakech,Rooms were dirty - toilets and bed sheets Ther...,neg,August 2019,2.9,Ahmed,Egypt
21000,Hotel Marrakech le Tichka,Marrakech,This hotel appears to be completely dysfunctio...,floors so filthy,made to wait hour on arriving and disinterest...,also pool side had dirty nappies in the garde...,neg,August 2019
21001,Hotel Marrakech le Tichka,Marrakech,Architecture,pos,July 2019,7.5,Aimar,Estonia
21002,Hotel Marrakech le Tichka,Marrakech,service,neg,July 2019,7.5,Aimar,Estonia

In [91]:
agadir=pd.read_csv('BookingReviewsAgadirV1.csv',encoding='utf-8',error_bad_lines=False)
agadir

C:\Users\ATLAS PRO ELECTRO\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

,hotel_name,ville,review,type_rev,stay_date,reviewer_rate,reviewer_name,reviewer_country
0,Riad Les Chtis D'Agadir,Agadir,Internet could be better,neg,November 2021,9.0,Vlad,Austria
1,Riad Les Chtis D'Agadir,Agadir,Location was great right near the cafes and ci...,pos,August 2021,10.0,Jannine,United States
2,Riad Les Chtis D'Agadir,Agadir,The location of the riad is very convenient fo...,pos,March 2020,10.0,Detlef,Germany
3,Riad Les Chtis D'Agadir,Agadir,"Nothing, except the Corona virus and the shut ...",neg,March 2020,10.0,Detlef,Germany
4,Riad Les Chtis D'Agadir,Agadir,The riad is beautiful with lovely unique decor...,pos,February 2020,10.0,Naomi,United Kingdom
...,...,...,...,...,...,...,...,...
18189,Agyad Maroc Appart-Hotel,Agadir,Quiet location,pos,December 2018,4.6,Anonymous,Morocco
18190,Agyad Maroc Appart-Hotel,Agadir,Beds not very comfortable Clogged toilets Show...,neg,December 2018,4.6,Anonymous,Morocco
18191,Dream Wavez Tamraght,Agadir,The place does not exist Scam,neg,November 2021,1.0,Hugo,France
18192,Dream Wavez Tamraght,Agadir,"Nothing, it doesn't exist",pos,September 2021,1.0,Anonymous,Belgium
18193,Dream Wavez Tamraght,Agadir,"The hotel does not exist, it's a scam don't be...",neg,September 2021,1.0,Anonymous,Belgium

In [92]:
north=pd.read_csv('BookingReviewsNorthmorocco.csv',encoding='utf-8',error_bad_lines=False)
north

C:\Users\ATLAS PRO ELECTRO\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

,hotel_name,ville,review,type_rev,stay_date,reviewer_rate,reviewer_name,reviewer_country
0,Aymane ROOFTOP Hotel,Chefchaouene,Clean room Different and wonderful terrace v...,pos,December 2021,10.0,Mohamed,Morocco
1,Aymane ROOFTOP Hotel,Chefchaouene,Staff is more than helpful!! The rooftop is a ...,pos,November 2021,10.0,Guillaume,Canada
2,Aymane ROOFTOP Hotel,Chefchaouene,The hotel staff are people who make you love t...,pos,November 2021,10.0,Robert,United States
3,Aymane ROOFTOP Hotel,Chefchaouene,"Great location in Medina, spotlessly clean, ve...",pos,October 2021,10.0,Karen,United Kingdom
4,Aymane ROOFTOP Hotel,Chefchaouene,"Staff friendly and helpful, perfect location i...",pos,October 2021,9.0,Jens,Germany
...,...,...,...,...,...,...,...,...
6749,Hotel Le Gardenia (ex Lutetia),Tangier,Dirty Dirty bed sheet Toilet is broken and d...,neg,July 2019,3.3,Dr,United Kingdom
6750,Hotel Le Gardenia (ex Lutetia),Tangier,Old Art Deco Hotel full of character Ideal lo...,pos,May 2019,9.2,Charlotte,United Kingdom
6751,Hotel Le Gardenia (ex Lutetia),Tangier,"Smelly bathroom, loud at night, food & drink o...",neg,May 2019,9.2,Charlotte,United Kingdom
6752,Hotel Le Gardenia (ex Lutetia),Tangier,One of the staff members who checked us in was...,pos,April 2019,3.3,Thomas,Australia
6753,Hotel Le Gardenia (ex Lutetia),Tangier,Room was full of insects and flys Bathroom wa...,neg,April 2019,3.3,Thomas,Australia

In [114]:
finaldata=kech.append(agadir).append(north)
finaldata.reset_index(drop=True, inplace=True)
#finaldata['reviewer_rate']=finaldata['reviewer_rate'].astype(float)/2
#finaldata=pd.read_excel('beforefinale.xlsx')
finaldata

,hotel_name,ville,review,type_rev,stay_date,reviewer_rate,reviewer_name,reviewer_country
0,Riad 7 Saints,Marrakech,Very friendly stuff! It was awesome to got so ...,pos,March 2020,10,Jan,Germany
1,Riad 7 Saints,Marrakech,This Riad surprised me in every way The facil...,pos,February 2020,NaN,NaN,NaN
2,Riad 7 Saints,Marrakech,You can hear almost everything that happens ou...,neg,February 2020,8.3,Elisa,NaN
3,Riad 7 Saints,Marrakech,The host was very friendly and accommodating ...,pos,January 2020,10,Andrean,Estonia
4,Riad 7 Saints,Marrakech,- Ridal was really a help for us! He was total...,pos,January 2020,9.0,Axel,Belgium
...,...,...,...,...,...,...,...,...
45946,Hotel Le Gardenia (ex Lutetia),Tangier,Dirty Dirty bed sheet Toilet is broken and d...,neg,July 2019,3.3,Dr,United Kingdom
45947,Hotel Le Gardenia (ex Lutetia),Tangier,Old Art Deco Hotel full of character Ideal lo...,pos,May 2019,9.2,Charlotte,United Kingdom
45948,Hotel Le Gardenia (ex Lutetia),Tangier,"Smelly bathroom, loud at night, food & drink o...",neg,May 2019,9.2,Charlotte,United Kingdom
45949,Hotel Le Gardenia (ex Lutetia),Tangier,One of the staff members who checked us in was...,pos,April 2019,3.3,Thomas,Australia
45950,Hotel Le Gardenia (ex Lutetia),Tangier,Room was full of insects and flys Bathroom wa...,neg,April 2019,3.3,Thomas,Australia

In [118]:
#df_mask=finaldata[finaldata['reviewer_rate']=='neg']

#df_mask

,hotel_name,ville,review,type_rev,stay_date,reviewer_rate,reviewer_name,reviewer_country
612,Dar El Qadi,Marrakech,The room lacked privacy a bit as it was openin...,you hear everything that goes on in the court...,"we really expected more!""",neg,January 2019,7.1
1150,Riad La Calèche,Marrakech,Sanitary not very clean In the sense of old ta...,but they are also found in other countries an...,"cold pool""",neg,June 2019,6.3
1248,Riad Du Petit Prince,Marrakech,"A haven of peace, a very calm and clean riad i...",prefer the upstairs bedrooms Two very small s...,"enough hot water slow to arrive""",neg,April 2019,9.2
1384,Riad Rose Du Desert,Marrakech,"Excellent Riad in a very good location, it is ...",not knowing Arabic to be able to mix better w...,"everything perfect""",neg,March 2020,9.0
1732,Riad Al Rimal,Marrakech,"The decor, the comfort, the incredible calm in...",and all the staff,"we have really enjoyed our stay""",neg,October 2021,10
2580,Dar Sholmes,Marrakech,"Cozy and clean structure, very kind and helpfu...",any taxi instead costs you 10euro,in fact on the way back we reached the airpor...,neg,May 2019,10
2969,Hôtel Ibn Batouta,Marrakech,"We are a couple with a child, we had an excell...",except when you indicate on booking that you ...,"it does not appear on the site""",neg,January 2020,9.0
3300,Riad Chorfa,Marrakech,The riad is very beautifully renovated The ro...,honey,and amlou for breakfast would have made it pe...,neg,January 2020,9.0
4463,Riad Taziri,Marrakech,"First of all, the host Mustafa and his family ...",if you've never been there - don't make the s...,"but that was just a minor inconvenience """,neg,November 2019,10
5260,Riad Pachavana,Marrakech,"The breakfast was nice, fresh orange juice, yo...",such of lack of an elevator But for us this ...,"because all bed rooms were on the first floor """,neg,September 2019,10
5636,Origin Hotels Riad Lhena,Marrakech,"Amazing breakfast, staff were very friendly an...",they kicked the ball in our direction as we w...,"but just watch out for them """,neg,February 2019,9.6
6277,Riad Challa Restaurant Spa & Heated Pool,Marrakech,Riad Challa is located just 5 minutes from the...,the first time it passes can give some respect,"but it is well lit but there is no problem """,neg,September 2019,9.6
6517,Riad Challa Restaurant Spa & Heated Pool,Marrakech,Central location right in the middle Very frie...,the rooms are a bit dark. Unfortunately,the intense chemical smell in our bathroom wa...,neg,March 2019,9.2
6561,Riad Challa Restaurant Spa & Heated Pool,Marrakech,Several things: we hired the taxi to pick us u...,I also asked for a taxi to pick me up from th...,after waiting at the airport I had to take a ...,neg,August 2019,4.6
6819,Riad Ysalis,Marrakech,"I normally don't take time to write reviews, b...",you have to pay extra (as we were told!!) Top...,the day we left the manager asked us to pay e...,neg,January 2020,1.0
7335,Riad La Rose D'orient,Marrakech,I never really felt that safe walking around t...,the friendly stuff managed a fair and comfort...,"we had a comfortable stay """,neg,February 2020,8.0
7668,Hotel & Spa Riad Dar El Aila,Marrakech,Sadly I really don't understand the good ratin...,the room we stayed the first night,as they didn’t have availability at the room ...,neg,August 2019,6.7
8008,Be Live Collection Marrakech Adults Only All i...,Marrakech,"We have just spent a week at your resort, and ...",in reception they were always rude and didn’t...,15h? How its possible i dont have my room cle...,neg,September 2019,2.9
8030,Riad Leila Marrakech,Marrakech,"Riad is absolutely lovely, decor, cleanliness,...",especially the shower/toilet The roof terrac...,"not just the eating area """,neg,December 2019,9.0
8582,Equity Point Marrakech,Marrakech,"This building was a big, beautiful old Riad wi...",but I wouldn't call it a bar We were expect...,but it was more like a hotel than a hostel an...,neg,July 2019,7.5
8999,Riad Azenzer,Marrakech,Our hostesses were very friendly and warm The...,was that one of the 3 room was quite smelly,"probably because of the drainage/sewage system """,neg,February 2019,9.2
9003,Riad Azenzer,Marrakech,"The breakfast was below average, because all t...",so had to just hold it Overall light in roo...,it’s just difficult to tell until you are the...,neg,March 2019,5.4
9255,Riad Amra,Marrakech,"This Riad has a bit of magic in it's design, b...",also the toilet flush was not always working ...,"feels a bit creepy at first """,neg,January 2020,8.0
12055,Riad Zinnha,Marrakech,"The Riad was beautiful, in a good location nea...",we did not provoke them in any shape or form ...,and luckily there was always the option to di...,neg,November 2019,8.3
12083,Riad Nejma Oriental,Marrakech,"The evening staff were wonderful, even prepari...",the speakers were in front of our bedroom It...,sound travels easier there Also the Riad is ...,neg,March 2019,9.6
12529,Riad Maizie,Marrakech,I booked it for it’s looks but the gem is in t...,the WiFi connection wasn’t working and when i...,it was really slow This wasn’t the property...,neg,February 2020,7.9
12770,Riad Mamahouse Marrakech,Marrakech,"We picked this riad for its location, a 5 minu...",Ramadan,"but they do """,neg,November 2019,8.0
12798,Mövenpick Hotel Mansour Eddahbi Marrakech,Marrakech,"The staff at the checking desk, they were ver...",and when we told them to add the price on our...,they (kindly) said that we had to pay right a...,neg,June 2021,9.0
14231,Savoy Le Grand Hotel Marrakech,Marrakech,There are very few positives to say about the ...,harassing my guests who coming to join me for...,I suggest additional training to the staff to...,neg,March 2019,5.8
14574,Es Saadi Marrakech Resort - Hotel,Marrakech,"The grounds Beautiful mature gardens, coverin...",the furniture is very old,and the bathrooms are old This Hotel is defi...,neg,January 2019,4.6
15032,Riad Al Tainam,Marrakech,"Personal was kind, roof terrace was comfortab...",little bit hard to understanding,but we did it French speakers are advantag...,neg,February 2019,8.3
15855,Dellarosa Boutique Hotel,Marrakech,"The pool is being renovated, and the noise fro...",not suitable for swimming and due to it's loc...,from our room all we could see was an apartme...,neg,February 2019,8.3
16107,Wazo Hotel,Marrakech,"Modern, clean, spacious, friendly staff, defin...",I found my car was hit by another car and lef...,they said they don’t have security cameras fo...,neg,June 2019,5.0
16953,Al Maaden Villa Hotel & Spa,Marrakech,"Nice and calm outside the city centre, Riad is...",kitchen poorly equipped (we used it once only),"loose fittings""",neg,April 2019,7.5
17014,Hotel Lawrence d'Arabie,Marrakech,We just stayed for a night near the train stat...,i hope there was an option for a brighter lig...,Maybe we just turned it on too cold that nig...,neg,September 2021,8.0
17319,Riad Moucharabieh,Marrakech,Its a wonderful escape from a bustle and hustl...,but it's a minor thing,since it's a place for holidays and I had goo...,neg,April 2019,8.3
18892,Hotel Le Grand Imilchil,Marrakech,"Breakfast was good, continental style, juice, ...",I had a tour reserved I asked the waiter to ...,he said OK but brought my breakfast later tha...,neg,May 2019,6.7
19170,El Andalous Lounge & Spa Hotel,Marrakech,"Noted many things, like the room's toilet we'r...",no water& heater in the room,"no answer from any service to bring tee or food""",neg,February 2020,5.0
20183,La Renaissance Hotel,Marrakech,"Staff were lovely, especially Doha, Haima and ...",once I checked in,I asked the receptionist if they could help b...,neg,October 2021,8.0
20885,Imperial Holiday Hôtel & spa,Marrakech,"This was a NIGHTMARE hotel Cold shower, Freez...",the hotel is in need of some serious investme...,i expect the owners dont care about being com...,neg,January 2019,3.8
20962,Hotel Marrakech le Tichka,Marrakech,We did not expect such a treatment from a 4 st...,the hotel is not well maintained (old furnitu...,"the breakfast was not good at all """,neg,September 2019,5.0

In [119]:
#finaldata=pd.read_excel('beforefinale.xlsx')

,Unnamed: 0,hotel_name,ville,review,type_rev,stay_date,reviewer_rate,reviewer_name,reviewer_country
0,22162,White Beach Resort Taghazout - Tout Compris,Agadir,I booked the swim up Room that has a private p...,neg,August 2021,1,Mehdi,United States
1,22166,White Beach Resort Taghazout - Tout Compris,Agadir,Nothing,pos,August 2020,1,Anonymous,Morocco
2,22167,White Beach Resort Taghazout - Tout Compris,Agadir,Everything,neg,August 2020,1,Anonymous,Morocco
3,22726,Hotel Sindibad,Agadir,Nothing,pos,January 2020,1,Louise,France
4,22727,Hotel Sindibad,Agadir,"Very very dirty bathroom, shower clogged with ...",neg,January 2020,1,Louise,France
...,...,...,...,...,...,...,...,...,...
45946,20913,Hotel Ichbilia فندق اشبيلية,Marrakech,Great location and friendly staff: you exit th...,neg,December 2019,NaN,NaN,NaN
45947,20939,Hotel Ichbilia فندق اشبيلية,Marrakech,The staff were unfriendly and they can’t speak...,neg,NaN,NaN,NaN,NaN
45948,20960,Hotel Marrakech le Tichka,Marrakech,"The staff didn’t speak English at all, the roo...",NaN,NaN,NaN,NaN,NaN
45949,20980,Hotel Marrakech le Tichka,Marrakech,"helpful friendly staff, location was good, out...",pos,NaN,NaN,NaN,NaN
45950,20989,Hotel Marrakech le Tichka,Marrakech,"Very friendly staff, specially in the restaura...",pos,September 2019,NaN,NaN,NaN

# #Saving the booking files after deleting all the empty rows (not classified)

In [133]:
finaldata.to_csv('beforefinale.csv',sep=';',encoding='utf-8',index=False)

In [131]:
#finaldata.drop('Unnamed: 0', axis=1, inplace=True)

After finding another error while watching our data in Excel we upload it again and clean it on special values

In [134]:
booking=pd.read_csv('beforefinale.csv',sep=';',encoding='utf-8')

In [137]:
booking.sort_values("type_rev", inplace = True)

In [151]:
booking=booking[(booking['type_rev']=='neg')| (booking['type_rev']=='pos')]

In [153]:
booking.to_csv('BOOKINGfinal.csv',sep=';',encoding='utf-8',index=False)

# MERGING THE FILES OF HOTELS AND THEIR CLASSIFICATION and correspondance

In [193]:
Tripinfoskech=pd.read_csv("KechInfo.csv",encoding='utf-8')
Tripinfoskech

,hotel_name,city,class,location,cleanliness,service,value
0,Riad 7 Saints,Marrakech,3.0,-1.0,-1.0,-1.0,-1.0
1,Riad Belko,Marrakech,3.0,4.5,4.5,4.5,4.5
2,Riad Palais Des Princesses,Marrakech,5.0,4.5,4.5,4.5,4.5
3,Riad Daria Suites & SPA,Marrakech,4.0,4.5,5.0,4.5,4.5
4,Riad 58 Blu,Marrakech,4.0,5.0,5.0,5.0,4.5
...,...,...,...,...,...,...,...
412,Imperial Holiday Hotel & Spa,Marrakech,4.0,3.5,3.0,3.0,3.0
413,Riad Marrakech House,Marrakech,-1.0,3.5,3.5,3.5,4.0
414,Upupa de l'Atlas,Marrakech,-1.0,4.0,4.5,4.5,4.5
415,Hotel Ichbilia,Marrakech,2.0,4.0,2.5,2.5,3.5
416,Hotel Marrakech Le Tichka,Marrakech,4.0,3.5,3.5,3.5,3.5

In [158]:
bookingkech=pd.read_csv('hotelsMarrakech.csv',encoding='utf-8')

In [199]:
linkskechtrip=pd.read_csv('links.csv')
links=linkskechtrip['links']
links

0      https://www.tripadvisor.com/Hotel_Review-g2937...
1      https://www.tripadvisor.com/Hotel_Review-g2937...
2      https://www.tripadvisor.com/Hotel_Review-g2937...
3      https://www.tripadvisor.com/Hotel_Review-g2937...
4      https://www.tripadvisor.com/Hotel_Review-g2937...
                             ...
434    https://www.tripadvisor.com/Hotel_Review-g2937...
435    https://www.tripadvisor.com/Hotel_Review-g2937...
436    https://www.tripadvisor.com/Hotel_Review-g2937...
437    https://www.tripadvisor.com/Hotel_Review-g2937...
438                                                    *
Name: links, Length: 439, dtype: object

In [198]:
j=0
bhotel=[]
bservice=[]
bvalue=[]
blinks=[]
bhotel=[]
bcity=[]
blocation=[]
bcleaness=[]
bclass=[]
links[438]='*'
for i,link in enumerate(links):
    if(link=='*'):
        blinks.append(link)
        bhotel.append('noHotel')
        bcity.append('Marrakech')
        bclass.append('-1')
        blocation.append('-1')
        bcleaness.append('-1')
        bservice.append('-1')
        bvalue.append('-1')
    else:
        blinks.append(link)
        bhotel.append(Tripinfoskech['hotel_name'][j])
        bcity.append(Tripinfoskech['city'][j])
        bclass.append(Tripinfoskech['class'][j])
        blocation.append(Tripinfoskech['location'][j])
        bcleaness.append(Tripinfoskech['cleanliness'][j])
        bservice.append(Tripinfoskech['service'][j])
        bvalue.append(Tripinfoskech['value'][j])
        j=j+1

In [202]:
bookingkech['hoteltrip']=bhotel
bookingkech['service']=bservice
bookingkech['value']=bvalue
bookingkech['link']=blinks
bookingkech['city']=bcity
bookingkech['location']=blocation
bookingkech['cleanliness']=bcleaness
bookingkech['class']=bclass

In [204]:
bookingkech.to_excel('hotels_mixte.xlsx')

In [209]:
correspondance_hotel=pd.read_excel('hotels_mixte.xlsx')
correspondance_hotel=correspondance_hotel[['hotels','hoteltrip','city']]
correspondance_hotel['hoteltrip'].fillna('noHotel', inplace=True)
correspondance_hotel['city'].fillna('Marrakech', inplace=True)
correspondance_hotel.to_csv('correspondace_HotelsKech.csv',encoding='utf-8')

# corresepance between north(tangier ..) and agadir hotel informations

In [210]:
Tripinfosnorth=pd.read_csv("AGNORTHInfo.csv",encoding='utf-8')
Tripinfosnorth

,hotel_name,city,class,location,cleanliness,service,value
0,Riad Les Chtis D'Agadir,Agadir,3.0,4.0,4.5,5.0,4.5
1,Robinson Agadir,Agadir,4.0,4.5,4.5,4.5,4.0
2,Tikida Golf Palace,Agadir,5.0,4.5,4.5,4.5,4.0
3,Residence Hoteliere Fleurie,Agadir,2.0,4.0,4.5,4.5,4.0
4,Hotel Timoulay & Spa Agadir,Agadir,4.0,4.0,5.0,4.5,4.5
...,...,...,...,...,...,...,...
172,Pension Safari,Tangier,3.0,1.0,1.5,1.0,-1.0
173,Residence Nardina Golden,Tetouan,3.0,-1.0,-1.0,-1.0,-1.0
174,UMH Tarik Hotel,Tangier,-1.0,3.0,3.0,3.0,3.5
175,Hotel Astoria,Tangier,-1.0,5.0,4.0,4.0,5.0
176,Hotel Le Gardenia,Tangier,-1.0,5.0,3.0,4.0,-1.0

In [247]:
links=pd.read_csv('LinksAgNorth.csv')
links=links['links']

In [224]:
agadir=pd.read_csv('hotelsAgadirV1.csv',encoding='utf-8')
north=pd.read_csv('hotelsNorthKingdom.csv',encoding='utf-8')

In [237]:
AGNR=pd.DataFrame()
row=[agadir['hotels'],north['hotel']]
AGNR=pd.concat(row,names='hotels')
AGNR

0                     Riad Les Chtis D'Agadir
1             ROBINSON AGADIR - All Inclusive
2      Tikida Golf Palace - Relais & Châteaux
3                 Résidence Hotelière Fleurie
4               Hotel Timoulay and Spa Agadir
                        ...
137                            Pension Safari
138                  Résidence NARDINA GOLDEN
139                           UMH Tarik Hotel
140                             hotel Astoria
141                        Hotel Le Gardenia
Length: 189, dtype: object

the too names of the same hotel in booking and trip advisor have the same index ,if a hotel exists just in one of these websites an * is placed on the name of this hotel

In [248]:
j=0
bhotel=[]
bservice=[]
bvalue=[]
blinks=[]
bhotel=[]
bcity=[]
blocation=[]
bcleaness=[]
bclass=[]
links[188]='*'
for i,link in enumerate(links):
    if(link=='*'):
        blinks.append(link)
        bhotel.append('noHotel')
        bcity.append(-1)
        bclass.append(-1)
        blocation.append(-1)
        bcleaness.append(-1)
        bservice.append(-1)
        bvalue.append(-1)
    else:
        blinks.append(link)
        bhotel.append(Tripinfosnorth['hotel_name'][j])
        bcity.append(Tripinfosnorth['city'][j])
        bclass.append(Tripinfosnorth['class'][j])
        blocation.append(Tripinfosnorth['location'][j])
        bcleaness.append(Tripinfosnorth['cleanliness'][j])
        bservice.append(Tripinfosnorth['service'][j])
        bvalue.append(Tripinfosnorth['value'][j])
        j=j+1

In [251]:
AGNRTH=pd.DataFrame()
AGNRTH['hotels']=AGNR
AGNRTH['hoteltrip']=bhotel
AGNRTH['service']=bservice
AGNRTH['value']=bvalue
AGNRTH['link']=blinks
AGNRTH['city']=bcity
AGNRTH['location']=blocation
AGNRTH['cleanliness']=bcleaness
AGNRTH['class']=bclass

In [254]:
AGNRTH=pd.read_excel('AGNRTH.xlsx')

In [255]:
AGNRTH=AGNRTH[['hotels','hoteltrip','city']]

In [256]:
AGNRTH.to_csv('AGNRTH.csv',index=False,encoding='utf-8')

In [258]:
corr=[AGNRTH,correspondance_hotel]
corrsp=pd.concat(corr)
corrsp

,hotels,hoteltrip,city
0,Riad Les Chtis D'Agadir,Riad Les Chtis D'Agadir,Agadir
1,ROBINSON AGADIR - All Inclusive,Robinson Agadir,Agadir
2,Tikida Golf Palace - Relais & Châteaux,Tikida Golf Palace,Agadir
3,Résidence Hotelière Fleurie,Residence Hoteliere Fleurie,Agadir
4,Hotel Timoulay and Spa Agadir,Hotel Timoulay & Spa Agadir,Agadir
...,...,...,...
434,Imperial Holiday Hôtel & spa,Imperial Holiday Hotel & Spa,Marrakech
435,Marrakech House,Riad Marrakech House,Marrakech
436,Upupa de l’Atlas,Upupa de l'Atlas,Marrakech
437,Hotel Ichbilia,Hotel Ichbilia,Marrakech
438,Hotel Marrakech le Tichka,Hotel Marrakech Le Tichka,Marrakech

In [262]:
corrsp=corrsp[(corrsp['city']=='Marrakech')|(corrsp['city']=='Agadir')|(corrsp['city']=='Tangier')]
corrsp.to_csv('correspondance_Hotels.csv',encoding='utf-8',index=False)

# recleaning tweets and sentiment analysis

In [39]:
tweets=pd.read_csv('Tweets_Rev_Final.csv',encoding='utf-8',sep=';')

In [40]:
tweets=tweets.drop_duplicates()

In [41]:
tweets=tweets.dropna()

In [42]:
tweets

,hotel_name,ville,review,date_of_review,reviewer_username,reviewer_location,likes,classification
0,Ryad Marrakech,Marrakech,REAL ESTATE IDF Marrakech RYAD in the heart of...,April 2010,trefleannonces,France,0.0,pos
1,Ryad Marrakech,Marrakech,What envy Technical stop to refresh and contin...,April 2010,guscall,France,0.0,neg
2,Ryad Marrakech,Marrakech,Technical stop to refresh and continue walking...,April 2010,Fotomaf,Spain,0.0,neg
3,Ryad Marrakech,Marrakech,Vds flight Marrakech - Girona Saturday April R...,April 2010,lavoc,France,0.0,pos
4,Ryad Marrakech,Marrakech,Vds place Marrakech - Girona Saturday April Ry...,April 2010,lavoc,France,0.0,pos
...,...,...,...,...,...,...,...,...
18857,Mirador Golf Appart-hotel,Cabo Negro,"traveling to Tetouan, Cabo Negro, Mirador Golf...",August 2019,Mehdimouchtar,ALL,0.0,pos
18858,Mirador Golf Appart-hotel,Cabo Negro,Cabo Negro: One night for in a Studio at the M...,June 2013,Okeydeal,ALL,0.0,pos
18859,Hotel Mauritania,Tangier,"Nice view: Hotel Mauritania Centre Tanger, Tan...",January 2016,vofnmaurita,Mauritania,0.0,pos
18860,Hotel Mauritania,Tangier,📷 Biggest boat in tangier (en Hotel Mauritania...,December 2015,Koukouhmohamed,Morocco,0.0,pos
18861,Hotel Mauritania,Tangier,Biggest boat in tangier @ Hotel Mauritania Tan...,December 2015,Koukouhmohamed,Morocco,0.0,pos

In [13]:
from textblob import TextBlob

In [15]:
res = TextBlob('the movie is goodly described')
print(res.sentiment.polarity)

0.7

In [17]:
def analyseSentiment(sentence):
    res=TextBlob(str(sentence))
    an=res.sentiment.polarity
    if(an<0):
        return('neg')
    elif an==0:
        return('ntr')
    else:
        return('pos')

In [43]:
tweets['classification']=tweets.apply(lambda row : analyseSentiment(row['review']), axis = 1)

In [47]:
def cleanrev(rev):
    rev=str(rev)
    rev.replace('@','')
    rev.replace('#','')
    rev.replace('RT','')
    rev.replace('\n','')
    rev.replace('"',"")
    rev.replace('(','')
    rev.replace(')','')
    rev.replace("'",'')
    rev.replace("\\",'')
    rev.replace('*','')
    rev.replace(';',' ')
    rev.replace(',',' ')
tweets.apply(lambda row : cleanrev(row['review']), axis = 1)

0        None
1        None
2        None
3        None
4        None
         ...
18857    None
18858    None
18859    None
18860    None
18861    None
Length: 14797, dtype: object

In [45]:
tweets['review']

0        REAL ESTATE IDF Marrakech RYAD in the heart of...
1        What envy Technical stop to refresh and contin...
2        Technical stop to refresh and continue walking...
3        Vds flight Marrakech - Girona Saturday April R...
4        Vds place Marrakech - Girona Saturday April Ry...
                               ...
18857    traveling to Tetouan, Cabo Negro, Mirador Golf...
18858    Cabo Negro: One night for in a Studio at the M...
18859    Nice view: Hotel Mauritania Centre Tanger, Tan...
18860    📷 Biggest boat in tangier (en Hotel Mauritania...
18861    Biggest boat in tangier @ Hotel Mauritania Tan...
Name: review, Length: 14797, dtype: object

In [46]:
tweets.to_csv('Tweets_Rev_Final.csv',encoding='utf-8',sep=';',index=False)